version: '3.7'
services:
  postgres:
    image: postgres:11.5
    restart: always
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: Winnica52
       POSTGRES_DB: businesshelper
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
