spring:
  application:
    name: course-catalog-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5438/businesshelper
    #    url: jdbc:postgresql://localhost:5432/businesshelper
    username: postgres
    password: Winnica52
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop #this recreates the db, not recommended for prod
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  h2:
    console:
      enabled: true
message: Hello from default profile